<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tux-button primary large fullwidth-ard-d0b-98f</name>
   <tag></tag>
   <elementGuidId>f2383ff6-5e27-4a03-9b1b-9f26749fdec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.tux-button.primary.large.fullwidth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add gift card to balance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c497548-83c3-4955-86fc-4d601964f39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tux-button primary large fullwidth</value>
      <webElementGuid>9d48e457-85b6-4e11-8aa8-49cd940778a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>tux-button-wrapper</value>
      <webElementGuid>fdf44565-a5e2-44fd-8e09-10cd9ed83a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;tux-button primary large fullwidth&quot;]</value>
      <webElementGuid>76ef74ae-c3fa-4e7f-921b-6bcbfa57a84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Gift Card/Page_Amazon Pay Gift Card/tux-button_Add gift card to balance-ft Card-d0b</value>
      <webElementGuid>f098b855-ebf4-4a98-a547-0e99fcb46b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ae9cef7-0d8a-46b8-8cb9-471c7c31c628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>df1b08f6-eeff-46f2-8663-8b9d640526e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
