<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tux-input_Add gift card to balance_claimCod_db10d1</name>
   <tag></tag>
   <elementGuidId>c72458f4-63ba-4678-a7ad-c9bd04d7b69b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#claim-Code-input-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tux-input[@id='claim-Code-input-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#claim-Code-input-box</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tux-input</value>
      <webElementGuid>c875d911-dda8-4e98-9956-962fcac84731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>claim-Code-input-box</value>
      <webElementGuid>7ef6d515-5978-4a2b-89e2-4c8130bd47ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Enter gift card code</value>
      <webElementGuid>0860e7c2-291b-42fd-a592-c2e315520e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>claimCode</value>
      <webElementGuid>ec056610-c1ce-4835-958e-275bc9c4000a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28839ad8-c89f-4670-a889-a95376c89c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>errormessage</name>
      <type>Main</type>
      <value>You seem to have entered an invalid Gift Card / Promo code. Please enter the alphanumeric Gift Card code.</value>
      <webElementGuid>8919cfb7-e0bc-4b9e-8026-dab262e8f5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>c66f8e6d-13cd-41c2-a152-a5de2787a549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>c395448a-fc5d-4de7-9657-95ad57bcc24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;claim-Code-input-box&quot;)</value>
      <webElementGuid>18266b30-45e4-4f86-97e4-dcaf54406ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//tux-input[@id='claim-Code-input-box']</value>
      <webElementGuid>f1babfe4-e81f-400c-953e-75c7332c948b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-gift-card-form']/div/div/div/tux-input</value>
      <webElementGuid>aae47895-853a-4c48-bd25-7bc2c6109de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add gift card to balance'])[1]/following::tux-input[1]</value>
      <webElementGuid>7bb03323-ee9b-430e-abb5-b6f3eb628ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹0.00'])[1]/following::tux-input[1]</value>
      <webElementGuid>0b75448d-cb79-434d-88ca-b252a5481ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e.g. 8U95-Y3E8CQ-39MPQ'])[1]/preceding::tux-input[1]</value>
      <webElementGuid>75c821b1-a09a-41e0-9173-5c10753d371e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add gift card to balance'])[2]/preceding::tux-input[1]</value>
      <webElementGuid>3fd1a77e-9262-4f0b-a619-7bcd404e0bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/tux-input</value>
      <webElementGuid>2db82087-e482-4d76-8ea5-54efe5bd829a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tux-input[@id = 'claim-Code-input-box' and @name = 'claimCode']</value>
      <webElementGuid>ef7a0ca5-2ecc-418b-8e74-551279a09d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
