<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Next</name>
   <tag></tag>
   <elementGuidId>d8d03b6f-a507-4e41-a11b-3f088197946a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-3 > span.a-button-inner > i.a-icon.a-icon-next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='a-autoid-3']/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;bubbles-container&quot;] >> internal:role=button[name=&quot;Next&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2cc293b7-1d8a-4c3c-8cd8-c521be00a656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-next</value>
      <webElementGuid>c3c9dffb-fd76-4afd-8671-c9f00e3c6582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>93ab8857-f182-4a0b-88be-4c8b32350b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-3&quot;)/span[@class=&quot;a-button-inner&quot;]/i[@class=&quot;a-icon a-icon-next&quot;]</value>
      <webElementGuid>7567322d-eb24-40db-8047-9cd777f2f419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a-autoid-3']/span/i</value>
      <webElementGuid>7a15effb-22f9-4fad-983f-fb2e125e1eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Business'])[1]/following::i[1]</value>
      <webElementGuid>488029f5-2c51-4c3b-8774-a0bfb7af0a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deal of the Day'])[1]/following::i[1]</value>
      <webElementGuid>294a9165-0154-485e-b99a-a4738cd60d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount grid'])[1]/preceding::i[1]</value>
      <webElementGuid>57b5eacd-ac8d-4ee7-adf6-70e8f25eace7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/a/span/i</value>
      <webElementGuid>3e2c3e12-3ae1-4384-a76f-536f3caa4be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>e804a622-6721-4339-b033-2f6356e52ce1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
