<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This order contains a gift_proceedToR_057b5e</name>
   <tag></tag>
   <elementGuidId>3de304d1-1016-4639-a457-3b02adbdd6bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;proceedToRetailCheckout&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='proceedToRetailCheckout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Proceed to Buy\n                    \n                    \n                \n                \n                    Buy Amazon items&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25cc7499-7e33-42e2-9648-52fc07ecabe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proceedToRetailCheckout</value>
      <webElementGuid>d19f3ecf-187b-4dd0-88cc-5e9bac0e222f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feature-id</name>
      <type>Main</type>
      <value>proceed-to-checkout-action</value>
      <webElementGuid>25faeb2a-5856-4000-85a0-a3669a7cb612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>b046b382-fb00-4bfa-8a35-7c8f900b263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>79d83cb9-e909-4c53-97b2-5866195e45dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proceed to checkout</value>
      <webElementGuid>bf8c3f84-1f52-47fa-ae41-d977e433cd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>sc-buy-box-ptc-button-announce</value>
      <webElementGuid>25fa77cd-68b7-4424-81c6-9b852f4951d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-buy-box-ptc-button&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>0ab30b1c-4e18-44a9-9f87-af1b2f25319e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='proceedToRetailCheckout']</value>
      <webElementGuid>825277c9-4848-48f5-b661-7ca51b39c977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sc-buy-box-ptc-button']/span/input</value>
      <webElementGuid>545ed3ce-8be1-4a98-8524-9335e2b03871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>abe46e08-fda8-4c93-8559-74d573f8d623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'proceedToRetailCheckout' and @type = 'submit']</value>
      <webElementGuid>e14ca9b0-ce48-4988-8e21-76b7b9bc3c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
