<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your password_signInSubmit</name>
   <tag></tag>
   <elementGuidId>e594ea55-21c3-4452-be11-1933e4cff76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sign in&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d8045fa-8951-4fcb-9aea-61b5fa13ce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInSubmit</value>
      <webElementGuid>888f0c8f-9454-4e20-8825-0cd2f205f719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>64a6741b-cb9b-41a2-bd02-f3a5fd053da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7c4444db-7697-4c5d-b519-30f7f0596c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>auth-signin-button-announce</value>
      <webElementGuid>03e9b65f-93f2-433f-890e-be11d8b403dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInSubmit&quot;)</value>
      <webElementGuid>a1c90e4c-ef33-43d3-87e9-47eb38d85db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInSubmit']</value>
      <webElementGuid>0b9b5e2e-ee7f-4463-bed0-c30091883cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='auth-signin-button']/span/input</value>
      <webElementGuid>4e6c7a1f-f65b-49ba-9b19-16de11a024c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>dc19cde6-b57f-4580-8af3-4b1d0b5f71b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInSubmit' and @type = 'submit']</value>
      <webElementGuid>178a480a-de97-4411-89f9-d0e9ecb2b4f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
