<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lists</name>
   <tag></tag>
   <elementGuidId>6e652546-c12b-4cdb-9dc4-c145760a832b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.al-intro-banner-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wishlist-page']/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Lists&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3a88b3f-48c0-4dc7-9cc2-1f9a94dd3132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>al-intro-banner-header</value>
      <webElementGuid>2a1f9a7b-0a36-4b44-87d1-731a416e377b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lists</value>
      <webElementGuid>c21f6983-1d7c-4ae5-980c-c1fa433ec0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wishlist-page&quot;)/div[@class=&quot;a-section al-intro-tab-content&quot;]/div[@class=&quot;a-section a-padding-base al-intro-content a-text-center&quot;]/div[@class=&quot;a-section al-intro-banner a-spacing-none&quot;]/span[@class=&quot;al-intro-banner-header&quot;]</value>
      <webElementGuid>7d38c509-045a-4bd8-9028-8fd5826f2f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wishlist-page']/div/div/div/span</value>
      <webElementGuid>1aeb394a-0d4d-471e-a3cd-55bf19146084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Friends'])[1]/following::span[1]</value>
      <webElementGuid>bc73a7fc-1095-452d-b217-fe99e93b3eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Lists'])[2]/following::span[1]</value>
      <webElementGuid>cbeca61e-602f-46d7-a138-4ab6e7efc723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='for all your shopping needs'])[1]/preceding::span[1]</value>
      <webElementGuid>c4add7ea-d078-4c2a-b3cd-c053fbe312db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::span[2]</value>
      <webElementGuid>68dd9003-29cc-427e-8da4-559911aa27da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lists']/parent::*</value>
      <webElementGuid>b1ce10b2-abe6-4395-bad7-2d252a6dd3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/span</value>
      <webElementGuid>da5ee271-dee1-45b0-a37a-a3ce89fcb6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lists' or . = 'Lists')]</value>
      <webElementGuid>dfd4e273-78a2-4819-bfab-733311bc1dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
