<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_There was a problem retrieving the co_d71a61</name>
   <tag></tag>
   <elementGuidId>476db29c-4633-4a1f-97e7-b8232adcc022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attach-sidesheet-view-cart-button > span.a-button-inner > input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[43]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cart&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5635d055-0827-43df-af08-93987533fb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>0542d99f-f9df-4e8a-b09f-8bd0c72d1578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e6f179cf-c246-436b-959a-f6a5b5af76f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>attach-sidesheet-view-cart-button-announce</value>
      <webElementGuid>fb01e9e7-661e-40e9-afe5-09fded838ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attach-desktop-sideSheet&quot;)/div[@id=&quot;attach-accessory-pane&quot;]/div[@class=&quot;a-scroller attach-accessory-section a-scroller-vertical&quot;]/div[@class=&quot;a-section a-spacing-none a-padding-base attach-primary-atc-confirm-box&quot;]/div[@id=&quot;attach-added-to-cart-message&quot;]/div[@class=&quot;a-fixed-left-grid-inner a-grid-vertical-align a-grid-top&quot;]/div[@class=&quot;a-fixed-left-grid-col a-col-right&quot;]/div[@class=&quot;a-row a-spacing-top-small&quot;]/form[@id=&quot;attach-view-cart-button-form&quot;]/span[@id=&quot;attach-sidesheet-view-cart-button&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>b80e5ea5-80eb-422b-a5ae-c53f1b7ddda1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[43]</value>
      <webElementGuid>55b61623-0daf-4253-90d9-4594bced3579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='attach-sidesheet-view-cart-button']/span/input</value>
      <webElementGuid>6ac73b95-345c-4397-bf16-5a7b508512b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/span/input</value>
      <webElementGuid>b2edbbea-7c55-4a6d-8ed5-37c9fb368fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>5331598f-f83f-4826-ba4c-60d91856345f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
