<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Change countryregion_nav-flyout-buffer-top</name>
   <tag></tag>
   <elementGuidId>b008eb08-e0ba-4c86-ae95-18bdb4c504fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-flyout-icp > div.nav-flyout-buffer-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-icp']/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nav-flyout-icp > .nav-flyout-buffer-top</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bba27546-43b3-4aab-8e80-45c24c7d5884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-flyout-buffer-top</value>
      <webElementGuid>70455acc-2558-45d6-b984-c3e2d84bbfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-icp&quot;)/div[@class=&quot;nav-flyout-buffer-top&quot;]</value>
      <webElementGuid>92842643-b215-4838-bf50-96dda6ec4122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-icp']/div[5]</value>
      <webElementGuid>fd477c8f-40f2-40bd-8037-4333278d9399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[5]</value>
      <webElementGuid>b410d568-ff5f-4f5a-be82-d601623d4990</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
