<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_India</name>
   <tag></tag>
   <elementGuidId>ea46978d-45f5-4624-ab3d-50c028f4e6e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-touch-link-country > span.icp-color-base</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-touch-link-country']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Choose a country/region for shopping. The current selection is India.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>304a1342-6fbb-4a8f-affa-d24dcfc3ef06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-color-base</value>
      <webElementGuid>0b56fa25-20c3-4f85-a3e8-57019f6eb9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India</value>
      <webElementGuid>cfe98606-24e7-43b4-bc47-68379ab05769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-touch-link-country&quot;)/span[@class=&quot;icp-color-base&quot;]</value>
      <webElementGuid>07614a16-f328-43a5-8c38-9156816aaff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='icp-touch-link-country']/span[2]</value>
      <webElementGuid>a9c51ace-3320-483f-98a7-0125c1b58ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[3]/following::span[3]</value>
      <webElementGuid>e82e615a-1124-4f89-9b65-ff30c49ed61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[6]</value>
      <webElementGuid>4f8cab16-e833-4db0-862b-ec31c82ddeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbeBooks'])[1]/preceding::span[1]</value>
      <webElementGuid>d9bf23df-a6fe-4b85-ab44-79b6139a3291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Books, art&amp; collectibles'])[1]/preceding::span[1]</value>
      <webElementGuid>81d505fb-2ca9-47bf-85d1-49cf31c8859a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='India']/parent::*</value>
      <webElementGuid>97d64876-e905-4cd3-b04c-030c526a4348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span[2]</value>
      <webElementGuid>4c888b95-f044-4d78-a455-fee4aed42ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'India' or . = 'India')]</value>
      <webElementGuid>b82cfa2f-e93c-474f-8592-36ccf7cf3ed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
