<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The UPI ID is in the format of nameph_029c41</name>
   <tag></tag>
   <elementGuidId>eaf9e0ec-4385-48e9-abdd-5923dacb325d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-tveV4H-134</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-tveV4H-134']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;EMI&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0206ff8c-6fcb-4e6f-8fd3-b5701be5cf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-tveV4H-134</value>
      <webElementGuid>559697c2-ef45-4496-9721-a1f9a3899ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b405971e-d956-4a98-b866-03b9651c8c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>f49e5db7-c612-49e7-a4d4-8be60c3b6bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=EMI&amp;isExpired=false&amp;paymentMethod=CC&amp;tfxEligible=false</value>
      <webElementGuid>75714729-c15c-4a39-9013-307d9a486fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-tveV4H-134&quot;)</value>
      <webElementGuid>ffcbd33d-cde9-4411-9cbd-a9956734936a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-tveV4H-134']</value>
      <webElementGuid>596fd02a-7d37-4227-957e-83424ee1a114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-tveV4H-133']/div/div/div/div/span/div/label/input</value>
      <webElementGuid>2a241d9e-ef9b-478c-93c0-5441f91b6c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span/div/label/input</value>
      <webElementGuid>b28f0b16-e8d2-48bd-8a01-d5ca0e77d434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-tveV4H-134' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>93258b04-54d7-4e41-9d28-a5dc65dfaf36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
