<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Another payment method_ppw-instrument_d02253</name>
   <tag></tag>
   <elementGuidId>2797cbca-5695-42dd-bec7-8847d71bd95a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-tveV4H-103</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-tveV4H-103']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18cee1e9-5872-472c-aad7-79e28e4081d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-tveV4H-103</value>
      <webElementGuid>d8e658ee-5d1b-4af9-bdeb-34cc7c9f731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7c838aa1-9811-4bea-b3ee-6342dfb133df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>cc012a51-eddf-4656-9273-47c4e26585c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SelectableAddCreditCard</value>
      <webElementGuid>dd887f8d-0949-40d6-b38d-b4115ede2406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-tveV4H-103&quot;)</value>
      <webElementGuid>81b111f4-cdc7-4516-8a69-0e7116cdf14b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-tveV4H-103']</value>
      <webElementGuid>13c2b6c0-15d5-4c81-84e4-9a253289d6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-tveV4H-102']/div/div/div/div/div/span/div/label/input</value>
      <webElementGuid>56c82320-b935-4169-a528-d88c4c92adc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>94b4b2a5-e828-49a1-8561-b06751dfc661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-tveV4H-103' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>fdbd414f-e00c-4ccf-b86e-4bbec5fe2fed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
