<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose an Option_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>23cbfdf7-249c-4f9b-9f1a-af74c6538cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-tveV4H-129</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-tveV4H-129']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Other UPI Apps&quot;i >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>075bb5f4-f03e-4c15-9887-ad672e3ca85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-tveV4H-129</value>
      <webElementGuid>4da305ee-607e-4fe9-b067-6905b386c114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>87e19298-2764-4130-ba27-4615597246c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>6f05fe4a-99d5-4948-a97c-56c6adbb3e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=amzn1.pm.poa.YW16bjEucG9hOmFtem4xLnBvYS5wb2RhLlVuaWZpZWRQYXltZW50c0ludGVyZmFjZTox.QTE1NFZNOE1PUjlPOEU&amp;isExpired=false&amp;paymentMethod=UnifiedPaymentsInterface&amp;tfxEligible=false</value>
      <webElementGuid>2f3248c3-04b7-4212-912e-5f9a2ce527b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-tveV4H-129&quot;)</value>
      <webElementGuid>68967903-80b4-4e3e-8e84-cd5dc3e326e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-tveV4H-129']</value>
      <webElementGuid>f47cb9f9-79f6-4fb6-86a2-9061a8562b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-tveV4H-128']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>2508803f-ccc3-4ce0-9c81-4527afa02a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/input</value>
      <webElementGuid>1e05bf28-6a30-4cce-9eb5-95235230cdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-tveV4H-129' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>021712e3-c0b9-4d25-97c3-64836018a270</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
