<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose an Option</name>
   <tag></tag>
   <elementGuidId>5abe4659-16a1-47d4-a28a-e8b8f1ceef6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-dropdown-prompt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='pp-tveV4H-113']/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;Choose an Option&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0097106-3019-46cf-a6fa-d209c0d86ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-prompt</value>
      <webElementGuid>aa0b78b0-12cf-407b-9443-1c02fe13d44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an Option</value>
      <webElementGuid>b6e65804-931e-425d-a525-8ffdab3d450b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-tveV4H-113&quot;)/span[@class=&quot;a-button-inner&quot;]/span[@class=&quot;a-button-text a-declarative&quot;]/span[@class=&quot;a-dropdown-prompt&quot;]</value>
      <webElementGuid>a9b73ee9-d72b-443e-8111-c04ea3f3ec32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pp-tveV4H-113']/span/span/span</value>
      <webElementGuid>a40da5d8-2827-411e-bbf9-610583960ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Banking'])[2]/following::span[5]</value>
      <webElementGuid>9fa4de98-1337-4502-82f2-6708459e8407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Banking'])[1]/following::span[6]</value>
      <webElementGuid>ee272c31-4d89-4bc8-97c2-eb72a6841bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other UPI Apps'])[1]/preceding::span[2]</value>
      <webElementGuid>06d3f6c6-7b2d-4c01-8e75-61608e6771f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please uncheck Amazon Pay Balance option to pay via UPI.'])[1]/preceding::span[3]</value>
      <webElementGuid>2ede173d-1174-46aa-bc50-e294475cd0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>fde59949-76fc-47fd-88b6-2c343c416a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Choose an Option' or . = 'Choose an Option')]</value>
      <webElementGuid>9e3f1b4b-a643-4bec-b4a7-5087bc250106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
