<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_options-container-063-40f-8d8</name>
   <tag></tag>
   <elementGuidId>3103e2b8-8ae8-4eba-b44a-4780cb56dbd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.option-host > button.options-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tux-option >> internal:has-text=&quot;Add Gift Card to Balance&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3936fe62-3e8a-4bdf-ac1f-b2c45e52942a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>options-container</value>
      <webElementGuid>d8849cfe-b88f-457e-b06d-12452a0979e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;option-host&quot;]/button[@class=&quot;options-container&quot;]</value>
      <webElementGuid>393f040b-a7e0-4845-a902-c6eb96b03727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Gift Card/Page_Add Money to Wallet/tux-option_Add Gift Card to Balance-let-063-40f</value>
      <webElementGuid>8dcd3358-107e-40eb-86d4-419be466c2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e9948505-f4f4-4be6-be30-bb1c6e90354c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>8c2106ef-4369-4982-a10e-77a11e9af498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
