<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payui-options-list_Do more with Amazon Pay _0335e9</name>
   <tag></tag>
   <elementGuidId>5d6562d4-c9df-40bb-b8c2-e2069c077cd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amazonPayBalanceDoMore</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//payui-options-list[@id='amazonPayBalanceDoMore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#amazonPayBalanceDoMore</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>payui-options-list</value>
      <webElementGuid>6c6fa33f-0429-4dc8-ab26-966fa017d327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showdivision</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7dd0831-ff5e-4c8d-93db-f3fdfe527134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data</name>
      <type>Main</type>
      <value>[{&quot;displayLabel&quot;:&quot;Add Gift Card to Balance&quot;,&quot;labelValue&quot;:&quot;Gift Card&quot;,&quot;redirectionUrl&quot;:&quot;/gp/aw/ya/gcb&quot;},{&quot;displayLabel&quot;:&quot;Add Cash to balance&quot;,&quot;labelValue&quot;:&quot;Cash Balance&quot;,&quot;redirectionUrl&quot;:&quot;/b?node=13494278031&quot;}]</value>
      <webElementGuid>3c6912e1-95fa-4f08-acd7-8201a344b761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amazonPayBalanceDoMore</value>
      <webElementGuid>63d4f8cb-8090-440f-a90b-41f61b9b20a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tux-widget hydrated tux-widget-animated</value>
      <webElementGuid>b383a037-488b-4a36-9b01-dc8acb5e2966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pagename</name>
      <type>Main</type>
      <value>ADD_MONEY.landing_page</value>
      <webElementGuid>77f0c5ce-c9b1-4896-a1a8-def67ae11aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>feafefa3-2d4e-439d-8667-69f2f9b69002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>slot19</value>
      <webElementGuid>6e5de418-bef6-48e5-a27c-ad906bc7f1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>content_impression.add-money.payui-options-list</value>
      <webElementGuid>9e7f1b4d-e29b-49a8-9aba-9adae39b275f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>9b6bd2-jjkme5-6q74zj-v2o9su</value>
      <webElementGuid>fdd0c931-8b7b-410d-9d41-7a0545042f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amazonPayBalanceDoMore&quot;)</value>
      <webElementGuid>e32d9fe6-e813-440f-8060-14fa53eb2c53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//payui-options-list[@id='amazonPayBalanceDoMore']</value>
      <webElementGuid>30d677ce-c941-4b1f-8ffd-86345059e56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slot19']/div/div/payui-options-list</value>
      <webElementGuid>4694a7b8-feb4-4928-b965-0fe5a7ec0ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//payui-options-list</value>
      <webElementGuid>2b40f613-afd2-48c1-8656-61f3d957667e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//payui-options-list[@id = 'amazonPayBalanceDoMore']</value>
      <webElementGuid>d268f83a-4e3c-475e-a3f3-c833c4111ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
