<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gift Cards</name>
   <tag></tag>
   <elementGuidId>3dcb7686-1311-4fdb-93d0-9b47331b0f3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Primary&quot;i >> internal:role=link[name=&quot;Gift Cards&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b8becc0-593d-4775-9a79-85f1f75ad71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gift-card-store/b/?ie=UTF8&amp;node=3704982031&amp;ref_=nav_cs_gc</value>
      <webElementGuid>c9ba1999-33a3-48b1-beb1-9ae4346ca345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>7254f91d-e31b-4da9-bd5e-f87d03f736ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>94681f27-55e9-4cb8-bbaa-135ec72ba285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>07f8761e-061c-4c9d-ba69-058c13194aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_3</value>
      <webElementGuid>b948fef4-cc0f-4238-9e8f-6be55e3cd345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_gc</value>
      <webElementGuid>d55e30a8-ed75-4622-a22b-ae352699b7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>5unrzj-p7jr1f-wh5lrr-kwvg08</value>
      <webElementGuid>7a926f1f-b383-49a4-8e44-900664cfa2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gift Cards</value>
      <webElementGuid>01d55e2e-bcee-4a09-921f-ec1dc0107d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/ul[@class=&quot;nav-ul&quot;]/li[@class=&quot;nav-li&quot;]/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>63056186-6287-4d87-a225-990f0a7c8c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/ul/li[4]/a</value>
      <webElementGuid>94fd70de-945f-43ce-80ef-8faa98ca5040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gift Cards')]</value>
      <webElementGuid>048e1890-cfcd-4b3c-ba0e-5e4da3a4014b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Pay'])[1]/following::a[1]</value>
      <webElementGuid>696daa16-32db-46e4-96d6-e87e85ea26c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell'])[1]/following::a[2]</value>
      <webElementGuid>14628ddc-eb89-47bc-8ae7-496148aed2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion'])[1]/preceding::a[1]</value>
      <webElementGuid>e1b352a8-ac0c-4e00-ab58-f6ca419d3fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Again'])[1]/preceding::a[2]</value>
      <webElementGuid>89ea4d5d-2537-4a06-8d5a-0bc042aa67ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gift-card-store/b/?ie=UTF8&amp;node=3704982031&amp;ref_=nav_cs_gc')]</value>
      <webElementGuid>9bc98721-beeb-4a74-83f9-7adb2bff2ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[4]/a</value>
      <webElementGuid>80b0456a-b06b-47b2-8879-5a11e53375cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gift-card-store/b/?ie=UTF8&amp;node=3704982031&amp;ref_=nav_cs_gc' and (text() = 'Gift Cards' or . = 'Gift Cards')]</value>
      <webElementGuid>ef3494d3-804c-4ea2-a90d-43cfa172e33b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
