<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_11</name>
   <tag></tag>
   <elementGuidId>1ecacfbd-91b5-4165-91e9-0646cb51bf9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._cDEzb_iveVideoWrapper_JJ34T.has-ive-video.ive-is-hovering > div.a-section.zg-bdg-ctr > div.a-section.zg-bdg-body.zg-bdg-clr-body.aok-float-left > span.zg-bdg-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p13n-asin-index-10']/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;#11&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0946637-0162-4a48-85a9-6a4b014abe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zg-bdg-text</value>
      <webElementGuid>208ea782-dc8a-41ac-9ceb-4cf71273d2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#11</value>
      <webElementGuid>df12bbb3-f467-409d-bbca-47cd10db1033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p13n-asin-index-10&quot;)/div[@class=&quot;_cDEzb_iveVideoWrapper_JJ34T has-ive-video ive-is-hovering&quot;]/div[@class=&quot;a-section zg-bdg-ctr&quot;]/div[@class=&quot;a-section zg-bdg-body zg-bdg-clr-body aok-float-left&quot;]/span[@class=&quot;zg-bdg-text&quot;]</value>
      <webElementGuid>0dbc1850-d21f-4090-aaea-83cab446190d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p13n-asin-index-10']/div/div/div/span</value>
      <webElementGuid>b3012802-6ec7-47f5-a6e3-d9e0bd85807a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹418.00'])[1]/following::span[1]</value>
      <webElementGuid>b2d75acb-4f8d-45a3-8d24-0eed6b8cae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#10'])[1]/following::span[7]</value>
      <webElementGuid>4239e5ca-5a95-4662-8471-e26272fcb0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch'])[2]/preceding::span[5]</value>
      <webElementGuid>28d28d9e-ad15-4eff-bda3-0fab44c7e84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#12'])[1]/preceding::span[6]</value>
      <webElementGuid>3225e0e8-2006-4149-95ce-5cb69e242ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#11']/parent::*</value>
      <webElementGuid>94ae03c1-5437-4616-ad78-db05c7a3e5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/span</value>
      <webElementGuid>0584e3ce-9da7-4b9b-9f92-b431338f0bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '#11' or . = '#11')]</value>
      <webElementGuid>6298f2d0-2539-4f47-978e-6327d141d845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
