<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Todays Deals</name>
   <tag></tag>
   <elementGuidId>5c004e7f-0a71-405d-9506-6e0b7c0823c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Today's Deals&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>848db7c4-e264-44db-9c40-e603a6a87344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/deals?ref_=nav_cs_gb</value>
      <webElementGuid>1438e607-964d-4879-88fe-5fee78b08789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>e630673b-0ea1-4eb8-930a-8fc0eeff9581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac2800e7-6029-4230-bea8-d1e12455f549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>e2e1242f-f55a-4593-ad52-eef068b533e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_3</value>
      <webElementGuid>c6728835-d263-4851-8152-dbe262a87079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_gb</value>
      <webElementGuid>fbcfc718-bdc8-4e8b-a0e2-1cc1bba3db96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>yh5vwb-o5kb94-vypb5e-521ifn</value>
      <webElementGuid>246e776a-5020-418d-b0e2-0117e021e8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today's Deals</value>
      <webElementGuid>6bb6e0fd-2f5a-4fa4-93ea-07ccf49d8ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/ul[@class=&quot;nav-ul&quot;]/li[@class=&quot;nav-li&quot;]/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>35d0bdc5-35ab-439f-8cbd-22626e82d486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/ul/li[4]/a</value>
      <webElementGuid>01ea5ec5-725f-4856-8a90-5c2b490a268d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestsellers'])[1]/following::a[1]</value>
      <webElementGuid>57e689bf-5e0c-42f6-a7d4-50e441035741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell'])[1]/following::a[2]</value>
      <webElementGuid>240216bb-bbe2-46fd-9ed6-5a958aba3a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobiles'])[1]/preceding::a[1]</value>
      <webElementGuid>6e5bbe09-17e5-43db-9004-0a3da1f2ec4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prime'])[1]/preceding::a[2]</value>
      <webElementGuid>3283fcbd-c3e6-458b-9be6-619e54aeaa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/deals?ref_=nav_cs_gb')]</value>
      <webElementGuid>0d55f9b6-33fb-494d-87e3-20a74d46b8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>0925d925-2ba9-49fc-9774-758eae70bfae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/deals?ref_=nav_cs_gb' and (text() = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Deals&quot;) or . = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Deals&quot;))]</value>
      <webElementGuid>63835c3b-3342-482b-b7c4-c301a9b7c9f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
