<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Starting 149  Headphones__fluid-quad-im_08202e</name>
   <tag></tag>
   <elementGuidId>6d0c509c-77b1-4bc0-ac2c-b54cd9f689cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardInstanceuT2SJJXQRB9tZYx8lTLnfg > div._fluid-quad-image-label-v2_style_fluidQuadImageLabelBody__3tld0 > div.a-section.a-spacing-small._fluid-quad-image-label-v2_style_gridRowOne__1t0zL > div.a-section.a-spacing-none._fluid-quad-image-label-v2_style_quadrantContainer__3TMqG._fluid-quad-image-label-v2_style_leftQuadrant__21nVp > a.a-link-normal._fluid-quad-image-label-v2_style_centerImage__30wh-.aok-block.image-window > div.a-section.a-spacing-none._fluid-quad-image-label-v2_style_fluidImageContainer__2SOMr > img._fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK._fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceuT2SJJXQRB9tZYx8lTLnfg']/div[2]/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;boAt&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ed632223-33d8-4756-b5c5-890a8f62a2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>boAt</value>
      <webElementGuid>b67c6c7a-cc58-42e6-8c36-79b23e684328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/31/img21/june/CE/GW/QC/PC/PC_QuadCard_boAt._SY232_CB553870684_.jpg</value>
      <webElementGuid>9d763ed7-8389-4ea5-adac-660bf9e14945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      <webElementGuid>214b0635-9bea-43a1-a480-eac1316b17c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/31/img21/june/CE/GW/QC/PC/PC_QuadCard_boAt._SY232_CB553870684_.jpg</value>
      <webElementGuid>378363a9-c1f2-47d4-ac67-539df6b8e77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceuT2SJJXQRB9tZYx8lTLnfg&quot;)/div[@class=&quot;_fluid-quad-image-label-v2_style_fluidQuadImageLabelBody__3tld0&quot;]/div[@class=&quot;a-section a-spacing-small _fluid-quad-image-label-v2_style_gridRowOne__1t0zL&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_quadrantContainer__3TMqG _fluid-quad-image-label-v2_style_leftQuadrant__21nVp&quot;]/a[@class=&quot;a-link-normal _fluid-quad-image-label-v2_style_centerImage__30wh- aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_fluidImageContainer__2SOMr&quot;]/img[@class=&quot;_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA&quot;]</value>
      <webElementGuid>a1478f92-cb24-43b8-b854-cd6b3ce55fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceuT2SJJXQRB9tZYx8lTLnfg']/div[2]/div/div/a/div/img</value>
      <webElementGuid>43796d6f-afe6-40fc-84d0-8c13e0c1ecc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='boAt']</value>
      <webElementGuid>17017878-91ab-4e01-9daa-87c7d1b0da64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/a/div/img</value>
      <webElementGuid>6cceb818-169b-4643-a3a1-02338f9a0f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'boAt' and @src = 'https://images-eu.ssl-images-amazon.com/images/G/31/img21/june/CE/GW/QC/PC/PC_QuadCard_boAt._SY232_CB553870684_.jpg']</value>
      <webElementGuid>1c26a496-bd2a-46dd-95ff-7292abba7b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
