<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Best seller_s-image</name>
   <tag></tag>
   <elementGuidId>b0d084be-7814-4cb3-b200-9b246fbe1f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='8fa963bb-a4f5-4b7b-8e09-7bb83a14495d']/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\38 fa963bb-a4f5-4b7b-8e09-7bb83a14495d&quot;] > .sg-col-inner > .s-widget-container > span > .puis-card-container > div > div > div > .puisg-col-inner > .s-product-image-container > div > .rush-component > .a-link-normal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e64c2263-7657-472d-a444-658fcc4f5571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>a6fdaf74-e500-4d13-a07f-64d5e9d6f9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/715qi-cIbML._AC_UY218_.jpg</value>
      <webElementGuid>00ecde89-68ca-4af6-8000-c4bc39b5ffdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/715qi-cIbML._AC_UY218_.jpg 1x, https://m.media-amazon.com/images/I/715qi-cIbML._AC_UY327_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/715qi-cIbML._AC_UY436_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/I/715qi-cIbML._AC_UY545_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/715qi-cIbML._AC_UY654_FMwebp_QL65_.jpg 3x</value>
      <webElementGuid>8cf6a080-d032-4b1b-8635-6fd23d9d257e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Don't Believe Everything You Think (English)</value>
      <webElementGuid>90b000e4-4fbd-4e9d-b603-01d85ac5194a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13dda332-ae69-4f24-86ed-c78c13480aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f30c9c1b-1a74-4dde-b89a-a2bf3c200640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>87cf75d2-0700-47e9-8a4b-853d5e7d9ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cbf48d4e-e8ca-46e2-a795-7ec5580c20e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8fa963bb-a4f5-4b7b-8e09-7bb83a14495d&quot;)/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_5&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-v32q3oilecxncz2g86s9h9jxjd6 s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section&quot;]/div[@class=&quot;puisg-row&quot;]/div[@class=&quot;puisg-col puisg-col-4-of-12 puisg-col-4-of-16 puisg-col-4-of-20 puisg-col-4-of-24 puis-list-col-left&quot;]/div[@class=&quot;puisg-col-inner&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-flex-expand-height puis puis-v32q3oilecxncz2g86s9h9jxjd6&quot;]/div[@class=&quot;aok-relative&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-fixed-height&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>53f0e7dc-83bf-4642-9171-5366439d93bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8fa963bb-a4f5-4b7b-8e09-7bb83a14495d']/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      <webElementGuid>328ded90-cbec-4093-9526-3677e954aadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;Don't Believe Everything You Think (English)&quot;]</value>
      <webElementGuid>60194fe8-9b2a-4ac3-86f0-dd769dd62f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      <webElementGuid>4336ad57-2127-4da0-aaae-b9edb0f54994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/715qi-cIbML._AC_UY218_.jpg' and @alt = concat(&quot;Don&quot; , &quot;'&quot; , &quot;t Believe Everything You Think (English)&quot;)]</value>
      <webElementGuid>0c245355-caaf-489c-84ff-c3680a681b34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
