<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_7</name>
   <tag></tag>
   <elementGuidId>0a02af4e-0048-48b1-859c-9f02677c0622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._cDEzb_iveVideoWrapper_JJ34T.has-ive-video.ive-is-hovering > div.a-section.zg-bdg-ctr > div.a-section.zg-bdg-body.zg-bdg-clr-body.aok-float-left > span.zg-bdg-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p13n-asin-index-6']/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;#7&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a4733b0b-8fdd-413c-9c25-ebdc96e1fb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zg-bdg-text</value>
      <webElementGuid>77c13572-4178-443f-a558-4f322b84c94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#7</value>
      <webElementGuid>272d902a-8404-4160-8be4-8072695158a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p13n-asin-index-6&quot;)/div[@class=&quot;_cDEzb_iveVideoWrapper_JJ34T has-ive-video ive-is-hovering&quot;]/div[@class=&quot;a-section zg-bdg-ctr&quot;]/div[@class=&quot;a-section zg-bdg-body zg-bdg-clr-body aok-float-left&quot;]/span[@class=&quot;zg-bdg-text&quot;]</value>
      <webElementGuid>bf6aac02-94f5-4583-8431-7628a6380749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p13n-asin-index-6']/div/div/div/span</value>
      <webElementGuid>ac988a2c-a97a-4f7b-abee-4d148ca05e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch'])[6]/following::span[1]</value>
      <webElementGuid>9a302d8a-843f-47b4-a36b-139ecdb826d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹189.00'])[1]/following::span[2]</value>
      <webElementGuid>97a425fe-3d5a-4440-b6bb-c35742553fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹499.00'])[1]/preceding::span[4]</value>
      <webElementGuid>2d7d9594-c604-4079-a18e-f1bb784786ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch'])[7]/preceding::span[7]</value>
      <webElementGuid>544178f5-a940-472e-8496-98528fd1fa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#7']/parent::*</value>
      <webElementGuid>2c267b69-edf8-4213-abe9-eb6dab82fcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/span</value>
      <webElementGuid>de899ddf-788c-44c3-af3e-43c1d93711b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '#7' or . = '#7')]</value>
      <webElementGuid>edbc859e-6a56-49e1-bdac-3133c35de119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
