<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to cart_1</name>
   <tag></tag>
   <elementGuidId>a19ac861-0a29-431e-a2be-7f2956f83fdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-2-announce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='a-autoid-2-announce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#a-autoid-2-announce</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0d22f6a-0b61-4cfd-8213-98cb9f09eef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>8c2afb52-4595-4bfe-acfa-0b66e1d4147b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>fdf92f9c-ad1c-4566-9d99-c4a1a0b35f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>259999f1-0339-4acd-8f2b-15b468ce77ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3df89e3a-9cab-4eb1-8cd0-f98564a90570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-2-announce</value>
      <webElementGuid>8a001027-b054-4540-b394-101a4bc9bf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>d6b1b784-967f-458d-b7c6-d976e34f1677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-2-announce&quot;)</value>
      <webElementGuid>24cd588d-2b93-4ae1-aa6f-140975f1a962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='a-autoid-2-announce']</value>
      <webElementGuid>5d02a1b1-f5ec-4fd0-b855-a214f1506db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-2']/span/button</value>
      <webElementGuid>3f3481ba-a258-409a-b4cc-df322160c5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon, 24 Mar'])[2]/following::button[1]</value>
      <webElementGuid>af4f987f-a30e-4f87-b94f-10adb45c0efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREE delivery'])[2]/following::button[1]</value>
      <webElementGuid>7de081b4-6d79-4f75-8088-25b9a4456beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limited time deal'])[1]/preceding::button[1]</value>
      <webElementGuid>2c5b2b5a-5763-4af5-8aac-4c63275430be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price, product page'])[3]/preceding::button[1]</value>
      <webElementGuid>0b7ab124-c1a7-4bac-8d82-7e0a95a6c3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/div/div/div[2]/div[6]/div/div/div[2]/div/form/div/div/span/div/span/span/button</value>
      <webElementGuid>d9a07591-8dfd-4173-8276-dae4c78be5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'submit.addToCart' and @type = 'button' and @id = 'a-autoid-2-announce' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>869a02a6-a03a-4fb2-ad4c-2a587852b818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
